version: "3" 
services:
  coldfusion:
    image: eaps-docker-coldfusion.bintray.io/cf/coldfusion:latest
    env_file: coldfusion.env
    ports:
    - 8500:8500
    - 5005:5005
    volumes:
    - ${PWD}/app:/app
    - ${PWD}/logs/:/opt/coldfusion/cfusion/logs/
    networks: 
      - web

networks:
  web:  
